sonar.projectKey=NoteVault
sonar.projectName=NoteVault_SEP_project
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=src/main/java

sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.java.libraries=target/dependency/*.jar

sonar.host.url=http://localhost:9000

sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# run with:
#mvn clean verify sonar:sonar -Dsonar.projectKey=NoteVault -Dsonar.token=$env:SONAR_TOKEN -Dsonar.host.url=http://localhost:9000