package model;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

public class LanguageModel {

    public record Language(String code, String fullName, String nativeName, Locale locale) {
        /*Auto-generated by Java Record to hold language data*/
    }

    private static final Map<String, Language> LANGUAGE_MAP = new LinkedHashMap<>();

    /**
     * Unmodifiable view of supported languages, keyed by language code.
     */
    public static final Map<String, Language> LANGUAGES = Collections.unmodifiableMap(LANGUAGE_MAP);

    public static final String DEFAULT_LANGUAGE_CODE = "EN";

    static {
        LANGUAGE_MAP.put("EN", new Language("EN", "English", "English", Locale.ENGLISH));
        LANGUAGE_MAP.put("FI", new Language("FI", "Finnish", "Suomi", Locale.of("fi")));
        LANGUAGE_MAP.put("NP", new Language("NP", "Nepali", "नेपाली", Locale.of("np")));
        LANGUAGE_MAP.put("MY", new Language("MY", "Burmese", "မြန်မာ", Locale.of("my")));
        LANGUAGE_MAP.put("SI", new Language("SI", "Sinhala", "සිංහල", Locale.of("si")));
        LANGUAGE_MAP.put("FA", new Language("FA", "Persian", "فارسی", Locale.of("fa")));
    }

    public static Language getByLocale(Locale locale) {
        return LANGUAGES.values().stream()
                .filter(l -> l.locale().getLanguage().equalsIgnoreCase(locale.getLanguage()))
                .findFirst()
                .orElse(LANGUAGES.get(DEFAULT_LANGUAGE_CODE));
    }

    /**
     * @return the default language entry.
     */
    @SuppressWarnings("unused")
    public static Language getDefault() {
        return LANGUAGES.get(DEFAULT_LANGUAGE_CODE);
    }
}
