package security;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;
import java.util.Arrays;
import java.util.Objects;

public class Validation {

    private static final String SIGNUP_ALL_FIELDS_ERROR = "signup.all_fields";
    private static final String LASTNAME_KEY = "lastName";
    private static final String USERNAME_KEY = "username";
    private static final String PASSWORD_KEY = "password";
    private static final String CONFIRM_PASSWORD_KEY = "confirmPassword";

    private static final Pattern DIGIT_PATTERN = Pattern.compile("\\d");
    private static final Pattern SPECIAL_CHAR_PATTERN = Pattern.compile("[!@#$%^&*()_+=\\-\\[\\]{};':\"\\\\|,.<>/?]");

    private Validation() {/* Private constructor to prevent instantiation */ }

    public record ValidationError(String key, Object[] args) implements controller.IValidationError {
        @Override
        public Object[] args() {
            return args == null ? new Object[0] : args;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof ValidationError other)) return false;
            if (!Objects.equals(key, other.key)) return false;
            return Arrays.equals(args(), other.args());
        }

        @Override
        public int hashCode() {
            int result = Objects.hashCode(key);
            result = 31 * result + Arrays.hashCode(args());
            return result;
        }

        @Override
        public String toString() {
            return "ValidationError[key=" + key + ", args=" + Arrays.toString(args()) + "]";
        }
    }

    public record ValidationResult(boolean success, Map<String, List<ValidationError>> errors) {
        /* Auto-generated by Java Record to hold validation results */
    }

    private static void addError(Map<String, List<ValidationError>> errors,
                                 String field,
                                 String key,
                                 Object... args) {

        errors.computeIfAbsent(field, k -> new java.util.ArrayList<>())
                .add(new ValidationError(key, args == null ? new Object[0] : args));
    }

    public static ValidationResult validateSignup(String firstName, String lastName,
                                                  String username, String email,
                                                  String password, String confirmPassword) {

        Map<String, List<ValidationError>> errors = new HashMap<>();

        firstName = checkValueAndTrim(firstName);
        lastName = checkValueAndTrim(lastName);
        username = checkValueAndTrim(username);
        email = checkValueAndTrim(email);
        password = checkValueAndTrim(password);
        confirmPassword = checkValueAndTrim(confirmPassword);

        if (!validateRequiredFields(firstName, lastName, username, email, password, confirmPassword)) {
            addError(errors, "firstName", SIGNUP_ALL_FIELDS_ERROR);
            addError(errors, LASTNAME_KEY, SIGNUP_ALL_FIELDS_ERROR);
            addError(errors, USERNAME_KEY, SIGNUP_ALL_FIELDS_ERROR);
            addError(errors, "email", SIGNUP_ALL_FIELDS_ERROR);
            addError(errors, PASSWORD_KEY, SIGNUP_ALL_FIELDS_ERROR);
            addError(errors, CONFIRM_PASSWORD_KEY, SIGNUP_ALL_FIELDS_ERROR);
        }

        // First name
        validateName(firstName, "firstName", errors, "First name");

        // Last name
        validateName(lastName, LASTNAME_KEY, errors, "Last name");

        // Username
        if (!username.matches("^[\\p{L}0-9_]{3,20}$")) {
            addError(errors,USERNAME_KEY, "signup.username_chars");
        }

        // Email
        if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
            addError(errors,"email", "signup.email_invalid");
        }

        // Password match
        if (!password.equals(confirmPassword)) {
            addError(errors,CONFIRM_PASSWORD_KEY, "signup.password_mismatch");
        }

        validatePassword(password, errors, PASSWORD_KEY);

        return new ValidationResult(errors.isEmpty(), errors);
    }

    // Validates that all required fields are filled
    public static boolean validateRequiredFields(String firstName, String lastName, String username,
                                                 String email, String password, String confirmPassword) {
        return !(firstName.isEmpty() || lastName.isEmpty() || username.isEmpty() ||
                email.isEmpty() || password.isEmpty() || confirmPassword.isEmpty());
    }

    // Validates name format
    public static void validateName(String value, String field, Map<String, List<ValidationError>> errors, String label) {
        if (value == null || value.isBlank()) {
            return;
        }

        if (value.length() < 2 || value.length() > 50) {
            addError(errors, field, "signup.name_length", label);
            return;
        }

        if (!value.matches("^[\\p{L}\\s\\-'/]+$")) {
            addError(errors, field, "signup.name_invalid", label);
        }
    }

    // Validates the username format
    public static boolean validateUsername(String username) {
        // Allow letters (including Nordic chars), numbers, and underscores
        return username.matches("^[\\p{L}0-9_]{3,20}$");
    }

    public static void validatePassword(String password, Map<String, List<ValidationError>> errors, String field) {
        if (password == null || password.isBlank()) {
            return;
        }

        if (password.length() < 6) {
            addError(errors, field, "signup.password_too_short");
        }

        if (!DIGIT_PATTERN.matcher(password).find()) {
            addError(errors, field, "signup.password_missing_number");
        }

        if (!SPECIAL_CHAR_PATTERN.matcher(password).find()) {
            addError(errors, field, "signup.password_missing_special");
        }
    }

    // Validates the email format using regex pattern
    public static boolean validateEmailFormat(String email) {
        return email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$");
    }

    // Validates that password and confirm password fields match
    public static boolean validatePasswordMatch(String password, String confirmPassword) {
        return password.equals(confirmPassword);
    }

    public static ValidationResult validateUpdate(String lastName, String username, String password, String confirmPassword) {

        Map<String, List<ValidationError>> errors = new HashMap<>();

        lastName = checkValueAndTrim(lastName);
        username = checkValueAndTrim(username);
        password = checkValueAndTrim(password);
        confirmPassword = checkValueAndTrim(confirmPassword);

        // Required fields
        if (lastName.isBlank() || username.isBlank()) {
            addError(errors, LASTNAME_KEY, SIGNUP_ALL_FIELDS_ERROR);
            addError(errors, USERNAME_KEY, SIGNUP_ALL_FIELDS_ERROR);
        }

        // Last name validation
        validateName(lastName, LASTNAME_KEY, errors, "Last name");

        // Username validation
        if (!validateUsername(username)) {
            addError(errors, USERNAME_KEY, "signup.username_chars");
        }

        // Password OPTIONAL
        if (!password.isBlank()) {

            // Match
            if (!password.equals(confirmPassword)) {
                addError(errors, CONFIRM_PASSWORD_KEY, "signup.password_mismatch");
            }

            // Strength
            validatePassword(password, errors, PASSWORD_KEY);
        }

        return new ValidationResult(errors.isEmpty(), errors);
    }

    private static String checkValueAndTrim(String value) {
        return value == null ? "" : value.trim();
    }
}